/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;
 

public class App { 
    public static void main(String[] args) { 

        for (Naipe n: Naipe.values()){
            System.out.println(n.getSimbolo());
        }
    }
}
