/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import main.java.engtelecom.poo.Naipe;

public class App { 
    public static void main(String[] args) { 

        for (Naipe n: naipe.values()){
            System.out.println(n.toString());
        }
    }
}
