/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {
        final String BR = "Brasil"; // constante em Java

        System.out.println("Olá, " + nomeCompleto("Luiza", "Kuze"));
        System.out.println(verificaAprovacao(2));
    }

    public static String nomeCompleto(String primeiroNome, String segundoNome) {
        return primeiroNome + ' ' + segundoNome;
    } 

    // Se for maior que 7 é aprovado e reprovado caso contrário
    public static boolean verificaAprovacao(int nota) {
        return (nota>7);
    } 
}
